# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Test Build

on:
  push:
  workflow_dispatch:

jobs:
  maven_build:
    name: Maven-Build (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: start redpanda
        uses: redpanda-data/github-action@v0.1.3
        with:
          version: "latest"
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build with Maven
        run: mvn -B install --file pom.xml
